### ISSUE TITLE
重构颜色

### ISSUE THREAD

**Issue by himself65** [Himself65/luogu-material#1]
[![FcVeJA.md.png](https://s1.ax1x.com/2018/12/25/FcVeJA.md.png)](https://imgchr.com/i/FcVeJA)

- 左侧SideNav颜色过于单调

- 比赛列表的颜色不符合MD配色和设计，应当参考 [Card](https://material-components.github.io/material-components-web-catalog/#/component/card) 进行重新设计和布局

**Comment by himself65** [comment]
在洛谷4更新基本完全后将会继续更新该项目

**Comment by HoshinoTented** [comment]
那你是要等快一年了
